const NATIONS = [
  ["FR","France","fr","france"],
  ["BR","Brésil","br","bresil"],
  ["AR","Argentine","ar","argentine"],
  ["BE","Belgique","be","belgique"],
  ["EN","Angleterre","gb-eng","england"],
  ["PT","Portugal","pt","portugal"],
  ["ES","Espagne","es","spain"],
  ["DE","Allemagne","de","germany"],
  ["IT","Italie","it","italy"],
  ["NL","Pays-Bas","nl","netherlands"],
  ["HR","Croatie","hr","croatia"],
  ["MA","Maroc","ma","morocco"],
  ["DZ","Algérie","dz","algeria"],
  ["TN","Tunisie","tn","tunisia"],
  ["SN","Sénégal","sn","senegal"],
  ["CI","Côte d’Ivoire","ci","ivory coast"],
  ["CM","Cameroun","cm","cameroon"],
  ["NG","Nigeria","ng","nigeria"],
  ["GH","Ghana","gh","ghana"],
  ["ML","Mali","ml","mali"],
  ["EG","Égypte","eg","egypt"],
  ["ZA","Afrique du Sud","za","south africa"],
  ["CO","Colombie","co","colombia"],
  ["UY","Uruguay","uy","uruguay"],
  ["CL","Chili","cl","chile"],
  ["PE","Pérou","pe","peru"],
  ["EC","Équateur","ec","ecuador"],
  ["PY","Paraguay","py","paraguay"],
  ["VE","Venezuela","ve","venezuela"],
  ["MX","Mexique","mx","mexico"],
  ["US","États-Unis","us","usa"],
  ["CA","Canada","ca","canada"],
  ["CR","Costa Rica","cr","costa rica"],
  ["PA","Panama","pa","panama"],
  ["JM","Jamaïque","jm","jamaica"],
  ["JP","Japon","jp","japan"],
  ["KR","Corée du Sud","kr","south korea"],
  ["CN","Chine","cn","china"],
  ["AU","Australie","au","australia"],
  ["NZ","Nouvelle-Zélande","nz","new zealand"],
  ["SA","Arabie saoudite","sa","saudi arabia"],
  ["QA","Qatar","qa","qatar"],
  ["IR","Iran","ir","iran"],
  ["IQ","Irak","iq","iraq"],
  ["TR","Turquie","tr","turkey"],
  ["GR","Grèce","gr","greece"],
  ["CH","Suisse","ch","switzerland"],
  ["AT","Autriche","at","austria"],
  ["DK","Danemark","dk","denmark"],
  ["SE","Suède","se","sweden"],
  ["NO","Norvège","no","norway"],
  ["PL","Pologne","pl","poland"],
  ["UA","Ukraine","ua","ukraine"],
  ["RS","Serbie","rs","serbia"],
  ["SC","Écosse","gb-sct","scotland"],
  ["WA","Pays de Galles","gb-wls","wales"],
  ["IE","Irlande","ie","ireland"],
  ["NI","Irlande du Nord","gb-nir","northern ireland"],
  ["RO","Roumanie","ro","romania"],
  ["HU","Hongrie","hu","hungary"],
  ["CZ","Tchéquie","cz","czech republic"],
  ["SK","Slovaquie","sk","slovakia"],
  ["SI","Slovénie","si","slovenia"],
  ["GE","Géorgie","ge","georgia"],
  ["IS","Islande","is","iceland"],
  ["FI","Finlande","fi","finland"],
  ["AL","Albanie","al","albania"],
  ["BA","Bosnie-Herzégovine","ba","bosnia"],
  ["MK","Macédoine du Nord","mk","north macedonia"],
  ["ME","Monténégro","me","montenegro"],
  ["XK","Kosovo","xk","kosovo"],
  ["IL","Israël","il","israel"],
  ["AE","Émirats arabes unis","ae","united arab emirates"],
  ["JO","Jordanie","jo","jordan"],
  ["UZ","Ouzbékistan","uz","uzbekistan"],
  ["KZ","Kazakhstan","kz","kazakhstan"],
  ["IN","Inde","in","india"],
  ["ID","Indonésie","id","indonesia"],
  ["TH","Thaïlande","th","thailand"],
  ["VN","Vietnam","vn","vietnam"]
];

export async function GET(){
  const nationItems=NATIONS.map(([code,label,flagCode,query])=>({
    code,
    label,
    query,
    flagCode,
    flagUrl:`https://flagcdn.com/w160/${flagCode}.png`
  }));

  return Response.json(
    {
      nationItems,
      count:nationItems.length
    },
    {
      headers:{
        "Cache-Control":"public, s-maxage=86400, stale-while-revalidate=604800"
      }
    }
  );
}
